language: node_js
node_js:
  - 'node'
sudo: false # Enable docker based containers
cache:
  directories: # Cache npm install
    - node_modules
script:
  - npm test
after_script:
  - npm run submitCover
